name: Link
description: Add an awesome link to the list
labels: link
body:
  - type: input
    attributes:
      label: Paste the awesome URL here
    validations:
      required: true
  - type: textarea
    attributes:
      label: Summary
    validations:
      required: true
