name: Test
on: pull_request
jobs:
  pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm start
      - name: Check that there are no uncommitted changes
        run: ./.github/no-staged-uncommitted-files.sh
