name: Regenerate
on:
  push:
    branches:
      - master
jobs:
  regenerate:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm test
      - run: npm start
      - run: git config user.email bot@json-schema.org
      - run: git config user.name "JSON Schema"
      - run: git add README.md
      - run: git status
      - run: git commit --allow-empty -m "Regenerate README.md"
      - run: git log -1 -p
      - run: git push origin master
